### ISSUE TITLE
Release 1.4.0 for appium-dot-app

### ISSUE THREAD

**Issue by moizjv** [appium/appium-dot-app#486] opened 2015-05-08 21:09 UTC

**Comment by penguinho** [comment] 2015-05-17 10:28
@moizjv I need a new version in npm to builld this, The first version had issues I need the chromedriver fix to be in npm. I can't get all of the components (Selendroid won't build) building on my local machine properly so I can't release my local copy.

If someone can give me a build with pull 5101 merged I can copy it into the .app and it will work.

https://github.com/appium/appium/pull/5101

**Comment by penguinho** [comment] 2015-05-17 10:29
The app uses npm install to install appium and can't install from a commit number. So i just need a built copy to chuck into the .app

**Comment by moizjv** [comment] 2015-05-18 03:43
@penguinho i think we would need a patch release for that. @jlipps you want me to cherry pick #5101 and release a patch?

**Comment by penguinho** [comment] 2015-05-18 11:07
@moizjv thanks, I just need a zip file or something with the built version that I can put in the .app I'd use my own but I can't get selendroid to work with reset.sh on my machine. Probably something with my java/mvn/android sdks setup

**Comment by moizjv** [comment] 2015-05-21 07:21
@penguinho https://github.com/appium/appium/releases/tag/v1.4.1 here you go. It is also released on npm! let me know if you need any thing more. Thanks!

**Comment by penguinho** [comment] 2015-05-21 08:31
@moizjv The issue is still happening. I can't npm install 1.4.1 from the .app. If you check out the app source, build the app, and run it in Xcode you will see the error after about 30 seconds

**Comment by naveenjammula** [comment] 2015-06-01 05:01
when mac version of appium 1.4.1 will be released ??

**Comment by penguinho** [comment] 2015-06-01 08:58
@moizjv, can you give me a built version of appium in a zip file and I can put this out. We can resolve the npm install issue later. I would just build it myself but I can seem to get Selendroid to build on my machine.

**Comment by moizjv** [comment] 2015-06-03 16:41
@penguinho sorry for delay, I have sent 1.4.1 over slack. Let me know if you need any thing else. Thanks

**Comment by penguinho** [comment] 2015-06-04 11:21
OK, I want to fix a few issues (Android inspector not working mainly) in the .app before releasing. I'll get it out before Monday

**Closed** 2015-06-08 10:22 UTC
