### ISSUE TITLE
Unable to Run Doctor

### ISSUE THREAD

**Issue by chandanch** [appium/appium-dot-app#558] opened 2016-05-18 05:59 UTC
When I try to run appium-doctor I get the error as:

 Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Appium Version:** 1.5.2(Acra)
**OS:** Mac OS X 10.11

I installed appium doctor using: 
1. npm install -g appium-doctor
2. Next i moved the appium-doctor to /Applications/Appium.app/Contents/Resources/node_modules/appium/bin/ 

This did not work, Please help

**Comment by edgy360** [comment] 2016-05-18 06:12
Please see https://github.com/appium/appium-dot-app/issues/540

Doctor needs to be run independent of the app for this current release. The issue is fixed in the next update.

**Closed by edgy360** 2016-05-18 06:12 UTC

**Comment by chandanch** [comment] 2016-05-18 10:53
when will the new version be released? will it be released today or tomorrow?

**Comment by chandanch** [comment] 2016-05-18 10:53
I need to test my app using, How to get the updated version?

**Comment by edgy360** [comment] 2016-05-18 11:25
It's released monthly. Please see the original issue I linked to as it can be run standalone from the main app (i.e. you don't need to wait for the next update).
