### ISSUE TITLE
Incorrect inspection of controls (offset)

### ISSUE THREAD

**Issue by igalep** [appium/appium-dot-app#409] opened 2014-11-10 14:28 UTC
I'm using Appium 1.3.1 , and while I'm trying to inspect some controls , the actual marking is in offset agains real control.
Pls see as it described in the snapshot.

![1](https://cloud.githubusercontent.com/assets/3533224/4977240/79c98e3e-68f6-11e4-8745-ecd4318bb04e.png)

Any idea how to fix it ?

10x

**Comment by p00j4** [comment] 2015-01-10 08:58
@penguinho : yes I had the similar issue #388 , and I could out that its was because of keypad's ui comes in pageSource xml, so even if its hidden due to any other ui, it claims for its presence, so for the work around of this issue @igalep - don't rely on other controls to hide the keypad rather close/hide it every time after you are done with the respective component. [Though it increases the test time which even I want to cut down but this is how page source is retrieved, @bootstraponline : had you face this & find any work around in ruby  ! ]

**Comment by igalep** [comment] 2015-01-18 14:08
@p00j4 , I think that I'm missing something , I've tried to open / close the keyboard , but the issue still remain ...

@edgy360 , is there any update regarding the inspector issue ?

Thanks

**Comment by p00j4** [comment] 2015-01-18 16:30
@igalep : then it looks like multiple screens in same pageSource [other other on is hidden but still identified ] --> its not solution for work around --> try using random tap at a place where in no action happens which will behave like refresh [the latest pagesource will be fetched -->so shall solve the problem]

**Comment by igalep** [comment] 2015-01-19 09:00
@p00j4 - sorry but I still did't understand the solution / workaround :)
I do see that the keyboard being inspected by the inspector eventhough it's not being visible.
But the question is, what can I do in order overcome the issue ? (the random taping as you suggested didn't work...)

you can see @ attached snapshot, there is a keyboard which is hidden....
![screen shot 2015-01-19 at 10 57 57 am](https://cloud.githubusercontent.com/assets/3533224/5797902/1b315e46-9fca-11e4-86f2-8f7023781418.png)

**Comment by p00j4** [comment] 2015-01-19 11:44
@igalep : if you are sure about the keyboard then identify which action brings it in front [just before you start facing this issue ] and close it front script like "done" tap . Ex. you tap/sendkeys in your textfield to add and it automatically brings the keypad in front so close it by script before proceeding for the next action

**Comment by igalep** [comment] 2015-01-19 11:56
@p00j4 : I think there is a confusion :)

The offset I see is within the inspector , there is no code involve , I just click on "magnifier" button, and getting an offset just after the inspector is being launched...

**Comment by igalep** [comment] 2015-01-25 12:16
Anything new with the described  issue ?

Thanks

**Comment by edgy360** [comment] 2015-01-25 17:44
No update from me yet. I have tried looking into it a few times but can’t figure out what is going wrong.=

**Comment by penguinho** [comment] 2015-01-25 19:05
It has to do with the letter boxing. I think we are not accounting for the unused space on the sides. I think it has to do with the work to make the inspector resizable.

**Comment by igalep** [comment] 2015-01-27 11:13
@edgy360  - do you have this issue on your side as well ? (reproducible)

@penguinho  - maybe I didn't understand you correctly , but the inspector window was maximized , and not resized ...

**Comment by penguinho** [comment] 2015-01-27 17:31
@igalep exactly. It used to be of a fixed size and not adjustable to be maxmized

**Comment by igalep** [comment] 2015-01-28 13:28
@penguinho - What do you mean ? Appium's inspector window is fully open (entire screem) what I'm doing wrong ?

**Comment by edgy360** [comment] 2015-01-28 13:52
You aren't doing anything wrong. The Inspector window never was resizable before, but the issue is caused by it having different aspect ratios for the image view.

Sent from my iPhone

**Comment by igalep** [comment] 2015-01-28 14:00
An updated snapshot

![screen shot 2015-01-28 at 3 29 54 pm](https://cloud.githubusercontent.com/assets/3533224/5938758/af4a90e6-a706-11e4-9a5e-f33d15276dfc.png)

**Comment by p00j4** [comment] 2015-01-28 14:05
@igalep : what @penguinho and @edgy360  mean is 
Don't expand or resize the inspector screen, [resize has issue with image view]
let it be as it is in its default fix size
Ex. my same screen [Done button] looks different in resized view and so better to stick with default screen size of inspector

**Comment by igalep** [comment] 2015-01-28 14:07
@p00j4 - What I'm asking , is what is "default fix size" ?

**Comment by p00j4** [comment] 2015-01-28 14:11
when inspector opens thats default fix size, don't just resize it

**Comment by igalep** [comment] 2015-01-28 14:14
The problem is that it keep persistency , once you change the sizes , it continue to open the window with last size you've used

**Comment by p00j4** [comment] 2015-01-28 14:14
oh I got it, you have sometimes used "zoom" under "window" and so every time you open inspector its coming in zoomed by default so you don't
suggestion: go to window-->zoom it should reset it back if not then resize inspector window for precision
if nothing works then just remove appium.app and download a new 1 and then you will find the "default screen size"

**Comment by p00j4** [comment] 2015-01-28 14:15
ya I was true :-)

**Comment by igalep** [comment] 2015-01-28 15:18
Ok , I'll try , but it's kind of odd :)

**Closed** 2015-02-24 16:59 UTC
Labels: Bug, Inspector
